### ISSUE TITLE
[ALL] Todo List Reminder

### ISSUE THREAD

**Issue by ValentinVERGEZ** [PyroTeam/robocup-pkg#58]
#### Description

Issue "fourre tout" listant toutes les petites choses à faire qui ne mérite pas à elle seule leur issue mais qu'on ne doit pas oublier.
#### Listing
- [ ] Retirer le g_init tout pourri dans gazebo_to_ros.
- [ ] Normalisation du format représentant nos Points dans les paramètres ROS. Normalisation à appliquer par exemple au tf_broadcaster.
- [ ] Gérer une compilation "RELEASE", avec par exemple le define NDEBUG aux COMPILE_FLAGS afin de désactiver les assert. Retirer les options de debug, etc
- [ ] Reprendre les remarques de la PR #54

**Comment by ValentinVERGEZ** [comment]
Ajout de:
- [ ] Gérer une compilation "RELEASE", avec par exemple le define NDEBUG aux COMPILE_FLAGS afin de désactiver les assert. Retirer les options de debug, etc
